// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDNzO7gl58LK94xZj3O4y0yh0v07cIzXc',
    appId: '1:941240450759:web:0e439de9c8ee32300788e2',
    messagingSenderId: '941240450759',
    projectId: 'metix-5a27b',
    authDomain: 'metix-5a27b.firebaseapp.com',
    databaseURL: 'https://metix-5a27b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'metix-5a27b.appspot.com',
    measurementId: 'G-RPK9D4MM5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv4HRFhUJYRKzFyjNg2H8bKSwpcCFctfc',
    appId: '1:941240450759:android:20b37d524eb38d0c0788e2',
    messagingSenderId: '941240450759',
    projectId: 'metix-5a27b',
    databaseURL: 'https://metix-5a27b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'metix-5a27b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD82fj7B-eK8uvEoqdPOQ-z1WUEz89IvOU',
    appId: '1:941240450759:ios:8e84ef8bdb3cda9c0788e2',
    messagingSenderId: '941240450759',
    projectId: 'metix-5a27b',
    databaseURL: 'https://metix-5a27b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'metix-5a27b.appspot.com',
    iosClientId: '941240450759-0srkvglf1rg69d3h859qdnb3hqr8oge5.apps.googleusercontent.com',
    iosBundleId: 'com.swirl.metix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD82fj7B-eK8uvEoqdPOQ-z1WUEz89IvOU',
    appId: '1:941240450759:ios:8e84ef8bdb3cda9c0788e2',
    messagingSenderId: '941240450759',
    projectId: 'metix-5a27b',
    databaseURL: 'https://metix-5a27b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'metix-5a27b.appspot.com',
    iosClientId: '941240450759-0srkvglf1rg69d3h859qdnb3hqr8oge5.apps.googleusercontent.com',
    iosBundleId: 'com.swirl.metix',
  );
}
